### ISSUE TITLE
[Rules | ES, TS]: 'naming-convention' and 'no-unused-vars' doesn't work together

### ISSUE THREAD

**Issue by sashaqred** [akveo/styleguide#20]
I can't write code like that:
```
const _exhaustiveCheck: never = value;
```

Error "Variable name `_exhaustiveCheck` must match one of the following formats: camelCase, UPPER_CASE" appears.
After deleting `_` appears another error "'exhaustiveCheck' is assigned a value but never used. Allowed unused vars must match /^_/u"

**Comment by zankevich** [comment]
> I thought about unused variables in the context of the `exhaustive check` pattern in TypeScript. https://medium.com/technogise/type-safe-and-exhaustive-switch-statements-aka-pattern-matching-in-typescript-e3febd433a7a

Hm...
Don't know but my personal preference is to disable this rule `allowed unused vars must match /^_/u`.
